// There are 4 JSON objects in this file. Each object has EQUAL NUMBER OF KEYS, which means that, for example, key 5 in asstetsUKR corresponds to key 5 in webPagesOfAssetsUKR and to key 5 in assetsENG, webPagesOfAssetsUKR.
// That kind of order should be kept to allow switching between languages without resetting choosen options.
// The \u200B symbol is MANDATORY IN ALL VALUES OF THE KEYS. It allows to segment the line without breaking the rules of word wrapping in Ukrainian and English. For example, when there is only a number left on the line, without name of the street.
// Usually \u200B symbop is used here after city names. E.g.  "[м. Київ,\u200B Лабораторний провулок, 12]"
// But in some occasions the part after \u200B is too long and does not fit into the line. So, we use it like "[м. Бровари, вул. Богдана\u200B Хмельницького, 1]".
//Where \u200B is used in key VALUES (not in keys!), there the line breaks. 

let assetsUKR = {
	"ТОВ «Метінвест Холдинг»": ["м. Київ,\u200B Лабораторний провулок, 12"],
	"ТОВ «Метінвест-СМЦ»": ["м. Київ,\u200B вул. Князів Острозьких, 8",
							"м. Львів,\u200B вул. Шевченка, 317-С",
							"м. Дніпро,\u200B вул. Солончакова, 101-А",
							"м. Бровари, вул. Богдана\u200B Хмельницького, 1",
							"с. Святопетрівське,\u200B вул. Київська, 27",
							"м. Вінниця,\u200B вул. Грибоєдова 1-А",
							"м. Хмельницький,\u200B вул. Курчатова, 118-А",
							"м. Кременчук,\u200B вул. Ярмаркова 1-Б",
							"м. Тернопіль,\u200B вул. Поліська, 11",
							"м. Кривий Ріг,\u200B Широківське шосе, 8",
							"м. Миколаїв,\u200B вул. Яворницького, 28",
							"смт. Васищеве,\u200B вул. Промислова, 15-А",
							"м. Одеса,\u200B Новомосковська дорога, 23/1",
							"м. Одеса,\u200B Старокиївське шосе, 21",
							"м. Брошнів-Осада,\u200B вул. 22-го Січня, 28-Б",],
	"ТОВ «Метінвест Діджитал»": ["м. Київ,\u200B Лабораторний провулок, 12"],
	"ПрАТ «Запоріжсталь»": ["м. Запоріжжя,\u200B Південне шосе, 72"],
	"ТОВ «Юністіл»": ["м. Кривий Ріг,\u200B вул. Окружна, 127/10"],
	"ПрАТ «Каметсталь»": ["м. Кам'янське,\u200B вул. Соборна, 186",
							"м. Кам'янське,\u200B вул. Колеусівська, 1"],
	"Spartan UK PLC": ["Gateshead,\u200B NE8 2RD Ropery Road"],
	"Metinvest Trametal SpA": ["San Giorgio Di Nogaro,\u200B 44 Enrico Fermi Street"],
	"Ferriera Valsider SpA": ["Vallese di Oppeano,\u200B 36 A. Salieri Street"],
	"Promet Steel JSC": ["Debelt, Administrative\u200B Building Promet Steel"],
	"ПрАТ «Запоріжкокс»": ["м. Запоріжжя,\u200B вул. Діагональна, 4"],
	"ПрАТ «Інгулецький гірничо-збагачувальний комбінат»": ["м. Кривий Ріг,\u200B вул. Рудна, 47"],
	"ПрАТ «Північний гірничо-збагачувальний комбінат»": ["м. Кривий Ріг,\u200B вул. Божедарівська, 1"],
	"ПрАТ «Центральний гірничо-збагачувальний комбінат»": ["м. Кривий Ріг,\u200B ПрАТ «ЦГЗК»"],
	"ТОВ «Збагачувальна фабрика «Свято-Варваринська»": ["с. Сергіївка,\u200B Верхній провулок, 44"],
	"ПрАТ «Шахтоуправління «Покровське»": ["с. Вдале,\u200B вул. Східна, 108"],
	"United Coal Company LLC": ["Johnson City,\u200B 2112 North Roan Street"],
	"ТОВ «Метінвест-Шиппінг»": ["м. Запоріжжя,\u200B Південне шосе, 72"],
	"ТОВ «Метінвест Січсталь»": ["м. Дніпро, вул. Князя\u200B Ярослава Мудрого, 53"],
	"ТОВ «Метінвест-Ресурс»": ["м. Запоріжжя,\u200B Південне шосе, 80"],
	"ТОВ «Вуглепромтранс»": ["м. Мирноград,\u200B вул. Соборна, 51"],
	"Metinvest International SA": ["Geneva,\u200B 2 Vallin Street",
									"Istambul,\u200B 2 Sedef Street, Block A, Apt. 4",
									" Beijing, 93# Jianguo Road,\u200B Building 5, No. 602",
									"Tunis, Du Lac de Constance\u200B Street, Carthage Building",
									"Dubai, Jebel Ali Free Zone,\u200B Building LOB17, 3rd floor"],
	"Metinvest Polska LLC": ["Katowice,\u200B 33 Varshavska Street"],
	"ТОВ «Метінвест Бізнес Сервіс»": ["м. Кривий Ріг,\u200B вул. Мусоргського, 15"],
	"ТОВ «Запорізький ливарно-механічний завод»": ["м. Запоріжжя,\u200B Південне шосе, 72",
													"м. Кривий Ріг,\u200B вул. Заводська, 1"],
	"ПрАТ «Запоріжвогнетрив»": ["м. Запоріжжя,\u200B Південне шосе, 22-Б",
								"м. Запоріжжя,\u200B вул. Теплична, 1"],
	"ПрАТ «Метінвест Покровськвугілля»": ["м. Покровськ,\u200B вул. Торгова, 106-А"],
	"ТОВ «Шахтобудівельна компанія»": ["м. Покровськ,\u200B вул. Залізнична, 82"],
	"ТОВ «Шахта «Свято-Покровська №3»": ["м. Покровськ,\u200B площа Шибанкова, 1-А"],
	"ТОВ «Свято-Іллінський машинобудівний завод»": ["м. Курахове,\u200B Промислова зона, 69/15"],
	"ПрАТ «Шахтобудмонтажне управління №1»": ["м. Курахове,\u200B Промислова зона, 69/15"],
	"Metinvest International Italia LLC": ["Vallese di Oppeano,\u200B 36 A. Salieri Street",
											"Genoa,\u200B 3 XII Ottobre Street"],
	"Trametal Deutschland LLC": ["Unterschleissheim,\u200B 40 Carl-von-Linde Street"],
	"Trametal Europe PLC": ["Hasselt,\u200B 9 Ilgat Lane"],
	"Metinvest Iberica LLC": ["Bilbao, 6 Rodriguez Arias\u200B Street, 2nd floor, unit 202-D"],
	"PROMET STEEL JSC Sales Department": ["Sofia,\u200B 1 Dobrudzha Street"],
	"Metinvest Carpathia LLC": ["Bucharest, 11A Turtureleloa\u200B Street, 2nd floor"],
	"Metinvest Business Service Europe LLC": ["Katowice,\u200B 33 Varshavska Street"]
}
let webPagesOfAssetsUKR = {
    "ТОВ «Метінвест Холдинг»": "metinvestholding.com",
	"ТОВ «Метінвест-СМЦ»": "metinvest-smc.com",
	"ТОВ «Метінвест Діджитал»": "metinvest.digital",
	"ПрАТ «Запоріжсталь»": "zaporizhstal.com",
	"ТОВ «Юністіл»": "metinvestholding.com",
	"ПрАТ «Каметсталь»": "dkhz.com.ua",
	"Spartan UK PLC": "spartan.metinvestholding.com/en",
	"Metinvest Trametal SpA": "trametal.metinvestholding.com/en",
	"Ferriera Valsider SpA": "valsider.metinvestholding.com/en",
	"Promet Steel JSC": "promet.metinvestholding.com/en",
	"ПрАТ «Запоріжкокс»": "zaporozhcoke.com",
	"ПрАТ «Інгулецький гірничо-збагачувальний комбінат»": "ingok.metinvestholding.com",
	"ПрАТ «Північний гірничо-збагачувальний комбінат»": "sevgok.metinvestholding.com",
	"ПрАТ «Центральний гірничо-збагачувальний комбінат»": "cgok.metinvestholding.com",
	"ТОВ «Збагачувальна фабрика «Свято-Варваринська»": "ofsv.metinvestholding.com",
	"ПрАТ «Шахтоуправління «Покровське»": "pokrovskoe.metinvestholding.com",
	"United Coal Company LLC": "ucc.metinvestholding.com",
	"ТОВ «Метінвест-Шиппінг»": "metinvestholding.com",
	"ТОВ «Метінвест Січсталь»": "metinvestholding.com",
	"ТОВ «Метінвест-Ресурс»": "metinvestholding.com",
	"ТОВ «Вуглепромтранс»": "metinvestholding.com",
	"Metinvest International SA": "metinvestholding.com",
	"Metinvest Polska LLC": "metinvestholding.com",
	"ТОВ «Метінвест Бізнес Сервіс»": "metinvestholding.com",
	"ТОВ «Запорізький ливарно-механічний завод»": "zlmz.com.ua",
	"ПрАТ «Запоріжвогнетрив»": "zaporozhogneupor.com",
	"ПрАТ «Метінвест Покровськвугілля»": "mpu.metinvestholding.com",
	"ТОВ «Шахтобудівельна компанія»": "metinvestholding.com",
	"ТОВ «Шахта «Свято-Покровська №3»": "metinvestholding.com",
	"ТОВ «Свято-Іллінський машинобудівний завод»": "metinvestholding.com",
	"ПрАТ «Шахтобудмонтажне управління №1»": "metinvestholding.com",
	"Metinvest International Italia LLC": "metinvestholding.com",
	"Trametal Deutschland LLC": "metinvestholding.com",
	"Trametal Europe PLC": "metinvestholding.com",
	"Metinvest Iberica LLC": "metinvestholding.com",
	"PROMET STEEL JSC Sales Department": "metinvestholding.com",
	"Metinvest Carpathia LLC": "metinvestholding.com",
	"Metinvest Business Service Europe LLC": "metinvestholding.com"
}
let assetsENG = {
	"Metinvest Holding LLC": ["Kyiv,\u200B 12 Laboratorny Lane"],
	"Metinvest-SMC LLC": ["Kyiv,\u200B 8 Kniaziv Ostrozkych Street",
						"Lviv,\u200B 317-C Shevchenko Street",
						"Dnipro,\u200B 101-A Solonchakova Street",
						"Brovary, 1 Bohdana\u200B Khmelnytskoho Street",
						"Sviatopetrivske,\u200B 27 Kyivska Street",
						"Vinnytsia,\u200B 1-A Hryboyedova Street",
						"Khmelnytsky,\u200B 118-A Kurchatova Street",
						"Kremenchuk,\u200B 1-B Yarmarkova Street",
						"Ternopil,\u200B 11 Poliska Street",
						"Kryvy Rih,\u200B 8 Shyrokivske Highway",
						"Mykolayiv,\u200B 28 Yavornytskoho Street",
						"Vasyshcheve,\u200B 15-A Promyslova Street",
						"Odesa,\u200B 23/1 Novomoskovska Road",
						"Odesa,\u200B 21 Starokyivske Highway",
						"Broshniv-Osada,\u200B 28-B 22th Sichnia Street"],
	"Metinvest Digital LLC": ["Kyiv,\u200B 12 Laboratorny Lane"],
	"Zaporizhstal PJSC": ["Zaporizhzhia,\u200B 72 Pivdenne Highway"],
	"Unisteel LLC": ["Kryvy Rih,\u200B 127/10 Okruzhna Street "],
	"Kametstal PJSC": ["Kamyanske,\u200B 186 Soborna Street",
						"Kamyanske,\u200B 1 Koleusivska Street"],
	"Spartan UK PLC": ["Gateshead,\u200B NE8 2RD Ropery Road"],
	"Metinvest Trametal SpA": ["San Giorgio Di Nogaro,\u200B 44 Enrico Fermi Street"],
	"Ferriera Valsider SpA": ["Vallese di Oppeano,\u200B 36 A. Salieri Street"],
	"Promet Steel JSC": ["Debelt, Administrative\u200B Building Promet Steel"],
	"ZaporizhCoke PJSC": ["Zaporizhzhia,\u200B 4 Diagonalna Street"],
	"Ingulets Iron Ore Enrichment Works PJSC": ["Kryvyi Rih,\u200B Rudna street, 47"],
	"Northern Iron Ore Enrichment Works PJSC": ["Kryvy Rih,\u200B 1 Bozhedarivska Street"],
	"Central Iron Ore Enrichment Works PJSC": ["Kryvy Rih, Central Iron Ore\u200B Enrichment Works PJSC"],
	"Sviato-Varvarinska Enrichment Plant LLC": ["Sergiivka,\u200B 44 Verhnii Lane"],
	"Pokrovske Mine Administration PJSC": ["Vdale,\u200B 108 Shidna Street"],
	"United Coal Company LLC": ["Johnson City,\u200B 2112 North Roan Street"],
	"Metinvest Shipping LLC": ["Zaporizhzhia,\u200B 72 Pivdenne Highway"],
	"Metinvest Sichsteel LLC": ["Dnipro, 53 Kniazia\u200B Yaroslava Mudroho Street"],
	"Metinvest Resourse LLC": ["Zaporizhzhia,\u200B 80 Pivdenne Highway"],
	"Vuglepromtrans LLC": ["Myrgorod,\u200B 51 Soborna Street"],
	"Metinvest International SA": ["Geneva,\u200B 2 Vallin Street",
									"Istambul,\u200B 2 Sedef Street, Block A, Apt. 4",
									" Beijing, 93# Jianguo Road,\u200B Building 5, No. 602",
									"Tunis, Du Lac de Constance\u200B Street, Carthage Building",
									"Dubai, Jebel Ali Free Zone,\u200B Building LOB17, 3rd floor"],
	"Metinvest Polska LLC": ["Katowice,\u200B 33 Varshavska Street"],
	"Metinvest Business Service LLC": ["Kryvy Rih,\u200B 15 Mussorgskoho Street"],
	"Zaporizhzhia Mechanical Foundry Plant LLC": ["Zaporizhzhia,\u200B 72 Pivdenne Highway",
													"Kryvy Rih,\u200B 1 Zavodska Street"],
	"Zaporizhvognetryv PJSC": ["Zaporizhzhia,\u200B 22-B Pivdenne Highway",
								"Zaporizhzhia,\u200B 1 Teplychna Street"],
	"Metinvest Pokrovskvugillia PJSC": ["Pokrovsk,\u200B 106-A Torgova Street"],
	"Mine-Building Company LLC": ["Pokrovsk,\u200B 82 Zaliznychna Street"],
	"Sviato-Pokrovska Mine №3 LLC": ["Pokrovsk,\u200B 1-A Shybankova Square"],
	"Sviato-Illinsky Machining Plant LLC": ["Pokrovsk,\u200B 69/15 Promyslova Zone"],
	"Mine Construction and Assembly Direcition №1 PJSC": ["Pokrovsk,\u200B 69/15 Promyslova Zone"],
	"Metinvest International Italia LLC": ["Vallese di Oppeano,\u200B 36 A. Salieri Street",
											"Genoa,\u200B 3 XII Ottobre Street"],
	"Trametal Deutschland LLC": ["Unterschleissheim,\u200B 40 Carl-von-Linde Street"],
	"Trametal Europe PLC": ["Hasselt,\u200B 9 Ilgat Lane"],
	"Metinvest Iberica LLC": ["Bilbao, 6 Rodriguez Arias\u200B Street, 2nd floor, unit 202-D"],
	"PROMET STEEL JSC Sales Department": ["Sofia,\u200B 1 Dobrudzha Street"],
	"Metinvest Carpathia LLC": ["Bucharest, 11A Turtureleloa\u200B Street, 2nd floor"],
	"Metinvest Business Service Europe LLC": ["Katowice,\u200B 33 Varshavska Street"]
}
let webPagesOfAssetsENG = {
    "Metinvest Holding LLC": "metinvestholding.com",
	"Metinvest-SMC LLC": "metinvest-smc.com",
	"Metinvest Digital LLC": "metinvest.digital/en",
	"Zaporizhstal PJSC": "zaporizhstal.com/en",
	"Unisteel LLC": "metinvestholding.com",
	"Kametstal PJSC": "metinvestholding.com",
	"Spartan UK PLC": "spartan.metinvestholding.com/en",
	"Metinvest Trametal SpA": "trametal.metinvestholding.com/en",
	"Ferriera Valsider SpA": "valsider.metinvestholding.com/en",
	"Promet Steel JSC": "promet.metinvestholding.com/en",
	"ZaporizhCoke PJSC": "zaporozhcoke.com",
	"Ingulets Iron Ore Enrichment Works PJSC": "ingok.metinvestholding.com",
	"Northern Iron Ore Enrichment Works PJSC": "sevgok.metinvestholding.com",
	"Central Iron Ore Enrichment Works PJSC": "cgok.metinvestholding.com",
	"Sviato-Varvarinska Enrichment Plant LLC": "ofsv.metinvestholding.com",
	"Pokrovske Mine Administration PJSC": "pokrovskoe.metinvestholding.com",
	"United Coal Company LLC": "ucc.metinvestholding.com",
	"Metinvest Shipping LLC": "metinvestholding.com",
	"Metinvest Sichsteel LLC": "metinvestholding.com",
	"Metinvest Resourse LLC": "metinvestholding.com",
	"Vuglepromtrans LLC": "metinvestholding.com",
	"Metinvest International SA": "metinvestholding.com",
	"Metinvest Polska LLC": "metinvestholding.com",
	"Metinvest Business Service LLC": "metinvestholding.com",
	"Zaporizhzhia Mechanical Foundry Plant LLC": "zlmz.com.ua",
	"Zaporizhvognetryv PJSC": "zaporozhogneupor.com",
	"Metinvest Pokrovskvugillia PJSC": "mpu.metinvestholding.com",
	"Mine-Building Company LLC": "metinvestholding.com",
	"Sviato-Pokrovska Mine №3 LLC": "metinvestholding.com",
	"Sviato-Illinsky Machining Plant LLC": "metinvestholding.com",
	"Mine Construction and Assembly Direcition №1 PJSC": "metinvestholding.com",
	"Metinvest International Italia LLC": "metinvestholding.com",
	"Trametal Deutschland LLC": "metinvestholding.com",
	"Trametal Europe PLC": "metinvestholding.com",
	"Metinvest Iberica LLC": "metinvestholding.com",
	"PROMET STEEL JSC Sales Department": "metinvestholding.com",
	"Metinvest Carpathia LLC": "metinvestholding.com",
	"Metinvest Business Service Europe LLC": "metinvestholding.com"
}

